# Generated by Django 5.2.17 on 2026-08-26 19:08

from django.db import migrations, models

FORWARD_SQL = (
    """
    ALTER TABLE persistence_dashboard
    ADD CONSTRAINT agora_dash_latest_owned_fk
    FOREIGN KEY (id, latest_revision_id)
    REFERENCES persistence_revision (dashboard_id, id)
    DEFERRABLE INITIALLY DEFERRED
    """,
    """
    ALTER TABLE persistence_dashboard
    ADD CONSTRAINT agora_dash_published_owned_fk
    FOREIGN KEY (id, published_revision_id)
    REFERENCES persistence_revision (dashboard_id, id)
    DEFERRABLE INITIALLY DEFERRED
    """,
    """
    ALTER TABLE persistence_revision
    ADD CONSTRAINT agora_rev_creator_owner_fk
    FOREIGN KEY (dashboard_id, created_by_id)
    REFERENCES persistence_dashboard (id, owner_id)
    DEFERRABLE INITIALLY DEFERRED
    """,
    """
    ALTER TABLE persistence_viewergrant
    ADD CONSTRAINT agora_grant_creator_owner_fk
    FOREIGN KEY (dashboard_id, created_by_id)
    REFERENCES persistence_dashboard (id, owner_id)
    DEFERRABLE INITIALLY DEFERRED
    """,
    """
    ALTER TABLE persistence_viewergrant
    ADD CONSTRAINT agora_grant_revoker_owner_fk
    FOREIGN KEY (dashboard_id, revoked_by_id)
    REFERENCES persistence_dashboard (id, owner_id)
    DEFERRABLE INITIALLY DEFERRED
    """,
    """
    ALTER TABLE persistence_auditevent
    ADD CONSTRAINT agora_audit_metadata_object
    CHECK (jsonb_typeof(metadata) = 'object')
    """,
    """
    CREATE FUNCTION agora_reject_retained_mutation() RETURNS trigger
    LANGUAGE plpgsql AS $$
    BEGIN
        RAISE EXCEPTION '% rows are append-only', TG_TABLE_NAME USING ERRCODE = '55000';
    END;
    $$
    """,
    """
    CREATE FUNCTION agora_guard_user_identity() RETURNS trigger
    LANGUAGE plpgsql AS $$
    BEGIN
        IF TG_OP = 'DELETE' THEN
            RAISE EXCEPTION 'users cannot be hard-deleted' USING ERRCODE = '55000';
        END IF;
        IF NEW.id IS DISTINCT FROM OLD.id OR NEW.soeid IS DISTINCT FROM OLD.soeid THEN
            RAISE EXCEPTION 'user identity is immutable' USING ERRCODE = '55000';
        END IF;
        RETURN NEW;
    END;
    $$
    """,
    """
    CREATE FUNCTION agora_guard_dashboard_identity() RETURNS trigger
    LANGUAGE plpgsql AS $$
    BEGIN
        IF TG_OP = 'DELETE' THEN
            RAISE EXCEPTION 'dashboards cannot be hard-deleted' USING ERRCODE = '55000';
        END IF;
        IF NEW.id IS DISTINCT FROM OLD.id OR NEW.owner_id IS DISTINCT FROM OLD.owner_id THEN
            RAISE EXCEPTION 'dashboard identity and ownership are immutable'
                USING ERRCODE = '55000';
        END IF;
        RETURN NEW;
    END;
    $$
    """,
    """
    CREATE FUNCTION agora_guard_revision_mutation() RETURNS trigger
    LANGUAGE plpgsql AS $$
    BEGIN
        IF TG_OP = 'DELETE' THEN
            RAISE EXCEPTION 'complete revisions cannot be deleted' USING ERRCODE = '55000';
        END IF;
        IF OLD.artifacts_locked = FALSE AND NEW.artifacts_locked = TRUE
           AND ROW(OLD.id, OLD.dashboard_id, OLD.number, OLD.created_by_id, OLD.created_at)
               IS NOT DISTINCT FROM
               ROW(NEW.id, NEW.dashboard_id, NEW.number, NEW.created_by_id, NEW.created_at) THEN
            RETURN NEW;
        END IF;
        RAISE EXCEPTION 'complete revisions are immutable' USING ERRCODE = '55000';
    END;
    $$
    """,
    """
    CREATE FUNCTION agora_guard_artifact_insert() RETURNS trigger
    LANGUAGE plpgsql AS $$
    DECLARE
        parent_locked boolean;
    BEGIN
        SELECT artifacts_locked INTO parent_locked
        FROM persistence_revision
        WHERE id = NEW.revision_id
        FOR KEY SHARE;
        IF parent_locked IS DISTINCT FROM FALSE THEN
            RAISE EXCEPTION 'artifacts cannot be added to a complete revision'
                USING ERRCODE = '55000';
        END IF;
        RETURN NEW;
    END;
    $$
    """,
    """
    CREATE FUNCTION agora_guard_grant_mutation() RETURNS trigger
    LANGUAGE plpgsql AS $$
    BEGIN
        IF TG_OP = 'DELETE' THEN
            RAISE EXCEPTION 'viewer grants cannot be deleted' USING ERRCODE = '55000';
        END IF;
        IF ROW(OLD.id, OLD.dashboard_id, OLD.viewer_id, OLD.created_by_id, OLD.created_at)
               IS DISTINCT FROM
               ROW(NEW.id, NEW.dashboard_id, NEW.viewer_id, NEW.created_by_id, NEW.created_at) THEN
            RAISE EXCEPTION 'viewer grant relationship is immutable' USING ERRCODE = '55000';
        END IF;
        IF OLD.revoked_at IS NOT NULL
           AND ROW(OLD.revoked_at, OLD.revoked_by_id)
               IS DISTINCT FROM ROW(NEW.revoked_at, NEW.revoked_by_id) THEN
            RAISE EXCEPTION 'viewer grant revocation is immutable' USING ERRCODE = '55000';
        END IF;
        RETURN NEW;
    END;
    $$
    """,
    """
    CREATE FUNCTION agora_check_revision_complete() RETURNS trigger
    LANGUAGE plpgsql AS $$
    DECLARE
        current_locked boolean;
        html_count bigint;
    BEGIN
        SELECT artifacts_locked INTO current_locked
        FROM persistence_revision
        WHERE id = NEW.id;
        SELECT count(*) INTO html_count
        FROM persistence_artifact
        WHERE revision_id = NEW.id AND kind = 'html';
        IF current_locked IS DISTINCT FROM TRUE OR html_count <> 1 THEN
            RAISE EXCEPTION 'a committed revision requires exactly one HTML artifact'
                USING ERRCODE = '23514';
        END IF;
        RETURN NULL;
    END;
    $$
    """,
    """
    CREATE FUNCTION agora_check_dashboard_latest() RETURNS trigger
    LANGUAGE plpgsql AS $$
    DECLARE
        current_latest uuid;
        expected_latest uuid;
    BEGIN
        SELECT latest_revision_id INTO current_latest
        FROM persistence_dashboard
        WHERE id = NEW.id;
        SELECT id INTO expected_latest
        FROM persistence_revision
        WHERE dashboard_id = NEW.id
        ORDER BY number DESC
        LIMIT 1;
        IF current_latest IS DISTINCT FROM expected_latest THEN
            RAISE EXCEPTION 'dashboard latest revision pointer is inconsistent'
                USING ERRCODE = '23514';
        END IF;
        RETURN NULL;
    END;
    $$
    """,
    """
    CREATE FUNCTION agora_check_revision_latest() RETURNS trigger
    LANGUAGE plpgsql AS $$
    DECLARE
        current_latest uuid;
        expected_latest uuid;
    BEGIN
        SELECT latest_revision_id INTO current_latest
        FROM persistence_dashboard
        WHERE id = NEW.dashboard_id;
        SELECT id INTO expected_latest
        FROM persistence_revision
        WHERE dashboard_id = NEW.dashboard_id
        ORDER BY number DESC
        LIMIT 1;
        IF current_latest IS DISTINCT FROM expected_latest THEN
            RAISE EXCEPTION 'dashboard latest revision pointer is inconsistent'
                USING ERRCODE = '23514';
        END IF;
        RETURN NULL;
    END;
    $$
    """,
    """
    CREATE TRIGGER agora_user_retention_guard
    BEFORE UPDATE OR DELETE ON persistence_user
    FOR EACH ROW EXECUTE FUNCTION agora_guard_user_identity()
    """,
    """
    CREATE TRIGGER agora_dashboard_retention_guard
    BEFORE UPDATE OR DELETE ON persistence_dashboard
    FOR EACH ROW EXECUTE FUNCTION agora_guard_dashboard_identity()
    """,
    """
    CREATE TRIGGER agora_revision_immutability_guard
    BEFORE UPDATE OR DELETE ON persistence_revision
    FOR EACH ROW EXECUTE FUNCTION agora_guard_revision_mutation()
    """,
    """
    CREATE TRIGGER agora_artifact_insert_guard
    BEFORE INSERT ON persistence_artifact
    FOR EACH ROW EXECUTE FUNCTION agora_guard_artifact_insert()
    """,
    """
    CREATE TRIGGER agora_artifact_immutability_guard
    BEFORE UPDATE OR DELETE ON persistence_artifact
    FOR EACH ROW EXECUTE FUNCTION agora_reject_retained_mutation()
    """,
    """
    CREATE TRIGGER agora_grant_immutability_guard
    BEFORE UPDATE OR DELETE ON persistence_viewergrant
    FOR EACH ROW EXECUTE FUNCTION agora_guard_grant_mutation()
    """,
    """
    CREATE TRIGGER agora_audit_append_only_guard
    BEFORE UPDATE OR DELETE ON persistence_auditevent
    FOR EACH ROW EXECUTE FUNCTION agora_reject_retained_mutation()
    """,
    """
    CREATE CONSTRAINT TRIGGER agora_revision_complete_check
    AFTER INSERT OR UPDATE OF artifacts_locked ON persistence_revision
    DEFERRABLE INITIALLY DEFERRED
    FOR EACH ROW EXECUTE FUNCTION agora_check_revision_complete()
    """,
    """
    CREATE CONSTRAINT TRIGGER agora_dashboard_latest_check
    AFTER INSERT OR UPDATE OF latest_revision_id ON persistence_dashboard
    DEFERRABLE INITIALLY DEFERRED
    FOR EACH ROW EXECUTE FUNCTION agora_check_dashboard_latest()
    """,
    """
    CREATE CONSTRAINT TRIGGER agora_revision_latest_check
    AFTER INSERT ON persistence_revision
    DEFERRABLE INITIALLY DEFERRED
    FOR EACH ROW EXECUTE FUNCTION agora_check_revision_latest()
    """,
)

REVERSE_SQL = (
    "DROP TRIGGER agora_revision_latest_check ON persistence_revision",
    "DROP TRIGGER agora_dashboard_latest_check ON persistence_dashboard",
    "DROP TRIGGER agora_revision_complete_check ON persistence_revision",
    "DROP TRIGGER agora_audit_append_only_guard ON persistence_auditevent",
    "DROP TRIGGER agora_grant_immutability_guard ON persistence_viewergrant",
    "DROP TRIGGER agora_artifact_immutability_guard ON persistence_artifact",
    "DROP TRIGGER agora_artifact_insert_guard ON persistence_artifact",
    "DROP TRIGGER agora_revision_immutability_guard ON persistence_revision",
    "DROP TRIGGER agora_dashboard_retention_guard ON persistence_dashboard",
    "DROP TRIGGER agora_user_retention_guard ON persistence_user",
    "DROP FUNCTION agora_check_revision_latest()",
    "DROP FUNCTION agora_check_dashboard_latest()",
    "DROP FUNCTION agora_check_revision_complete()",
    "DROP FUNCTION agora_guard_grant_mutation()",
    "DROP FUNCTION agora_guard_artifact_insert()",
    "DROP FUNCTION agora_guard_revision_mutation()",
    "DROP FUNCTION agora_guard_dashboard_identity()",
    "DROP FUNCTION agora_guard_user_identity()",
    "DROP FUNCTION agora_reject_retained_mutation()",
    "ALTER TABLE persistence_auditevent DROP CONSTRAINT agora_audit_metadata_object",
    "ALTER TABLE persistence_viewergrant DROP CONSTRAINT agora_grant_revoker_owner_fk",
    "ALTER TABLE persistence_viewergrant DROP CONSTRAINT agora_grant_creator_owner_fk",
    "ALTER TABLE persistence_revision DROP CONSTRAINT agora_rev_creator_owner_fk",
    "ALTER TABLE persistence_dashboard DROP CONSTRAINT agora_dash_published_owned_fk",
    "ALTER TABLE persistence_dashboard DROP CONSTRAINT agora_dash_latest_owned_fk",
)


class Migration(migrations.Migration):
    dependencies = [
        ("persistence", "0001_initial_domain"),
    ]

    operations = [
        migrations.AddField(
            model_name="revision",
            name="artifacts_locked",
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AddConstraint(
            model_name="viewergrant",
            constraint=models.CheckConstraint(
                condition=models.Q(("viewer", models.F("created_by")), _negated=True),
                name="agora_grant_owner_not_viewer",
            ),
        ),
        migrations.RunSQL(sql=FORWARD_SQL, reverse_sql=REVERSE_SQL),
    ]
