# Generated by Django 5.2.17 on 2026-08-26 19:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("persistence", "0002_database_invariants"),
    ]

    operations = [
        migrations.AlterField(
            model_name="auditevent",
            name="metadata",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
