# Generated by Django 5.2.17 on 2026-08-27

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("persistence", "0007_authentication_controls"),
    ]

    operations = [
        migrations.CreateModel(
            name="RenderAuthorization",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "token_digest",
                    models.CharField(editable=False, max_length=64, unique=True),
                ),
                (
                    "audience",
                    models.CharField(
                        choices=[("preview", "Owner preview"), ("viewer", "Published viewer")],
                        max_length=8,
                    ),
                ),
                ("viewer_auth_version", models.PositiveBigIntegerField(editable=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("expires_at", models.DateTimeField()),
                ("revoked_at", models.DateTimeField(blank=True, null=True)),
                (
                    "dashboard",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="render_authorizations",
                        to="persistence.dashboard",
                    ),
                ),
                (
                    "revision",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="render_authorizations",
                        to="persistence.revision",
                    ),
                ),
                (
                    "viewer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="render_authorizations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(fields=["expires_at"], name="agora_render_expiry_idx"),
                    models.Index(
                        fields=["dashboard", "viewer", "audience"],
                        name="agora_render_scope_idx",
                    ),
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(token_digest__regex="^[0-9a-f]{64}$"),
                        name="agora_render_token_digest_format",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(audience__in=["preview", "viewer"]),
                        name="agora_render_audience_valid",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(viewer_auth_version__gt=0),
                        name="agora_render_auth_version_positive",
                    ),
                ],
            },
        ),
    ]
