# syntax=docker/dockerfile:1.7

# The digest pins the uv toolchain and Python 3.14 Debian base used by the
# locked build.  The repository's treasury-analytics source is a development
# stand-in and is deliberately excluded from this production build.  The
# caller must provide the managed package wheel as a build-context artifact.
ARG UV_IMAGE=ghcr.io/astral-sh/uv:0.12.6-python3.14-trixie-slim@sha256:d61b872404ed1a0774e2098b5af64c178b59c99be171db6631455262bb0750b4
FROM ${UV_IMAGE} AS builder

# Keep the wheel's PEP 427 filename intact when it enters the build stage.  A
# release may override this with the exact managed artifact basename.
ARG TREASURY_ANALYTICS_WHEEL=managed/treasury_analytics-0.1.1-py3-none-any.whl
ARG TREASURY_ANALYTICS_WHEEL_SHA256

WORKDIR /app
ENV UV_PROJECT_ENVIRONMENT=/opt/venv \
    UV_COMPILE_BYTECODE=1 \
    UV_LINK_MODE=copy

# Keep registry dependency resolution cacheable. The local pyproject copied
# below is metadata-only: uv needs it to validate the path recorded in the
# lock, while --no-install-local excludes every local project. The managed
# wheel below is the only accepted runtime implementation.
COPY pyproject.toml uv.lock README.md ./
COPY packages/treasury-analytics/pyproject.toml packages/treasury-analytics/pyproject.toml
RUN --mount=type=cache,target=/root/.cache/uv \
    uv sync --locked --no-dev --no-install-project --no-install-local

COPY src src
COPY manage.py manage.py
COPY deploy deploy
RUN uv build --wheel --out-dir /tmp/agora-dist \
    && uv pip install --python /opt/venv/bin/python --no-deps /tmp/agora-dist/agora-*.whl

# A missing artifact fails the build instead of silently producing an image
# that can never connect to the managed Oracle package boundary.  The metadata
# assertion also rejects the repository's known local stand-in if it is passed
# accidentally under the managed artifact name.
COPY ${TREASURY_ANALYTICS_WHEEL} /tmp/
RUN set -eu; set -- /tmp/*.whl; test "$#" -eq 1; test -s "$1" \
    && test -n "${TREASURY_ANALYTICS_WHEEL_SHA256}" \
    && printf '%s  %s\n' "${TREASURY_ANALYTICS_WHEEL_SHA256}" "$1" \
        | sha256sum --check --status \
    && uv pip install --python /opt/venv/bin/python --no-deps "$1" \
    && /opt/venv/bin/python -c "import importlib.metadata as m, importlib, sys; summary=(m.metadata('treasury-analytics').get('Summary') or '').lower(); module=importlib.import_module('treasury_analytics'); invalid=('stand-in' in summary or 'development-only' in summary or getattr(module, 'AGORA_DEVELOPMENT_STAND_IN', False) or not hasattr(module, 'TAConnection')); sys.exit('managed treasury-analytics wheel must expose TAConnection and must not be the development stand-in') if invalid else None" \
    && uv pip check --python /opt/venv/bin/python \
    && rm "$1"

FROM python:3.14-slim-trixie@sha256:cae66f2ef0ec51a9891263eeee7f987dacf0a9879e8aa9353d5606e0530619a5 AS runtime

ARG APP_UID=10001
ARG APP_GID=10001

ENV PATH="/opt/venv/bin:${PATH}" \
    PYTHONDONTWRITEBYTECODE=1 \
    PYTHONUNBUFFERED=1 \
    AGORA_STATIC_ROOT=/var/lib/agora/static \
    PORT=8000

WORKDIR /app
COPY --from=builder /opt/venv /opt/venv
COPY --from=builder /app/manage.py /app/manage.py
COPY --from=builder /app/deploy /app/deploy

# Static output is generated by the one-shot `portal prepare` command after
# configuration injection. Supply this path as an explicit named mount: RW to
# the portal prepare job and RO to the trusted
# portal proxy/static adapter.  It is never mounted into content and is not a
# Docker-declared volume, so content cannot receive it implicitly.
RUN mkdir -p /var/lib/agora/static /var/lib/agora/artifacts \
    && groupadd --system --gid "${APP_GID}" agora \
    && useradd --system --uid "${APP_UID}" --gid "${APP_GID}" \
        --home-dir /nonexistent --shell /usr/sbin/nologin agora \
    && chown -R "${APP_UID}:${APP_GID}" /var/lib/agora

USER ${APP_UID}:${APP_GID}
# Artifacts are shared RW by portal and RO by content at the platform layer and
# remain private.  The static root is mounted explicitly by the prepare/proxy
# workloads only, so neither web service receives it.  This is the only
# image-declared volume; Docker VOLUME cannot express access modes.
VOLUME ["/var/lib/agora/artifacts"]
ENTRYPOINT ["python", "/app/deploy/entrypoint.py"]
CMD ["portal", "serve"]
