-- Agora Oracle schema.
--
-- Human-readable structural reference: tables, keys, constraints, and indexes.
-- Django migrations remain the executable source of truth for installs and upgrades.
-- Procedural triggers and data migrations intentionally stay in the migration files.

-- Application tables

CREATE TABLE TB_TA_AGORA_USER (
    PASSWORD NVARCHAR2(128) NULL,
    LAST_LOGIN TIMESTAMP NULL,
    ID VARCHAR2(32) NOT NULL PRIMARY KEY,
    SOEID NVARCHAR2(64) NULL UNIQUE,
    IS_ACTIVE NUMBER(1) NOT NULL CHECK (IS_ACTIVE IN (0,1)),
    IS_ADMINISTRATOR NUMBER(1) NOT NULL CHECK (IS_ADMINISTRATOR IN (0,1)),
    CREATED_AT TIMESTAMP NOT NULL,
    UPDATED_AT TIMESTAMP NOT NULL,
    AUTH_VERSION NUMBER(19) NOT NULL CHECK (AUTH_VERSION >= 0),
    CONSTRAINT AGORA_USER_CANONICAL_SOEID CHECK (
        REGEXP_LIKE(SOEID, '^[A-Z0-9][A-Z0-9._-]{0,63}$', 'c')
    ),
    CONSTRAINT AGORA_USER_AUTH_VERSION_PO831C CHECK (
        AUTH_VERSION > 0
    )
);

CREATE TABLE TB_TA_AGORA_DASHBOARD (
    ID VARCHAR2(32) NOT NULL PRIMARY KEY,
    NAME NVARCHAR2(200) NULL,
    DESCRIPTION NCLOB NULL,
    STATE NVARCHAR2(16) NULL,
    CREATED_AT TIMESTAMP NOT NULL,
    UPDATED_AT TIMESTAMP NOT NULL,
    OWNER_ID VARCHAR2(32) NOT NULL,
    LATEST_REVISION_ID VARCHAR2(32) NULL,
    PUBLISHED_REVISION_ID VARCHAR2(32) NULL,
    FIRST_PUBLISHED_AT TIMESTAMP NULL,
    PUBLICATION_VERSION NUMBER(19) NOT NULL CHECK (PUBLICATION_VERSION >= 0),
    LAST_PUBLISHED_AT TIMESTAMP NULL,
    PUBLICATION_NOTE NVARCHAR2(240) NULL,
    DATA_AS_OF TIMESTAMP NULL,
    FRESHNESS_INTERVAL_SECONDS NUMBER(19) NULL CHECK (FRESHNESS_INTERVAL_SECONDS >= 0),
    FRESHNESS_CONFIRMED_AT TIMESTAMP NULL,
    STALE_AFTER TIMESTAMP NULL,
    LAST_OWNERSHIP_TRANSFER_ID VARCHAR2(32) NULL UNIQUE,
    CONSTRAINT AGORA_DASHBOARD_VALID_STATE CHECK (
        STATE IN ('draft', 'published', 'unpublished', 'archived', 'deleted')
    ),
    CONSTRAINT AGORA_DASHBOARD_PUBLICATIO6DF3 CHECK (
        ((PUBLISHED_REVISION_ID IS NOT NULL AND STATE = 'published') OR (NOT (STATE = 'published'
        AND STATE IS NOT NULL) AND PUBLISHED_REVISION_ID IS NULL))
    ),
    CONSTRAINT AGORA_DASHBOARD_NAME_NOT_EMPTY CHECK (
        NOT (NAME IS NULL)
    ),
    CONSTRAINT AGORA_DASHBOARD_ID_OWNER_U6B9F UNIQUE (ID, OWNER_ID),
    CONSTRAINT AGORA_DASHBOARD_PUBLICATIOB209 CHECK (
        ((FIRST_PUBLISHED_AT IS NULL AND STATE = 'draft') OR (FIRST_PUBLISHED_AT IS NOT NULL AND
        STATE IN ('published', 'unpublished')) OR STATE IN ('archived', 'deleted'))
    ),
    CONSTRAINT AGORA_DASH_PUB_VERSION_TIME CHECK (
        ((LAST_PUBLISHED_AT IS NULL AND PUBLICATION_VERSION = 0) OR (LAST_PUBLISHED_AT IS NOT NULL
        AND PUBLICATION_VERSION > 0))
    ),
    CONSTRAINT AGORA_DASH_PUBLISHED_VERSIONED CHECK (
        (NOT (STATE = 'published' AND STATE IS NOT NULL) OR PUBLICATION_VERSION > 0)
    ),
    CONSTRAINT AGORA_DASH_FRESH_FIELDS_MATCH CHECK (
        ((FRESHNESS_CONFIRMED_AT IS NULL AND FRESHNESS_INTERVAL_SECONDS IS NULL AND STALE_AFTER IS
        NULL) OR (FRESHNESS_CONFIRMED_AT IS NOT NULL AND FRESHNESS_INTERVAL_SECONDS > 0 AND
        FRESHNESS_INTERVAL_SECONDS IS NOT NULL AND FRESHNESS_INTERVAL_SECONDS <= 31536000 AND
        STALE_AFTER IS NOT NULL))
    ),
    CONSTRAINT TB_TA_AGO_OWNER_ID_A3F88D8D_F
        FOREIGN KEY (OWNER_ID)
        REFERENCES TB_TA_AGORA_USER (ID)
        DEFERRABLE INITIALLY DEFERRED
);

CREATE TABLE TB_TA_AGORA_REVISION (
    ID VARCHAR2(32) NOT NULL PRIMARY KEY,
    NUMBER NUMBER(19) NOT NULL CHECK (NUMBER >= 0),
    CREATED_AT TIMESTAMP NOT NULL,
    CREATED_BY_ID VARCHAR2(32) NOT NULL,
    DASHBOARD_ID VARCHAR2(32) NOT NULL,
    ARTIFACTS_LOCKED NUMBER(1) NOT NULL CHECK (ARTIFACTS_LOCKED IN (0,1)),
    CONSTRAINT AGORA_REVISION_POSITIVE_NUMBER CHECK (
        NUMBER > 0
    ),
    CONSTRAINT AGORA_REVISION_DASHBOARD_N5E58 UNIQUE (DASHBOARD_ID, NUMBER),
    CONSTRAINT AGORA_REVISION_DASHBOARD_IA36D UNIQUE (DASHBOARD_ID, ID),
    CONSTRAINT TB_TA_AGO_CREATED_B_CC846DF3_F
        FOREIGN KEY (CREATED_BY_ID)
        REFERENCES TB_TA_AGORA_USER (ID)
        DEFERRABLE INITIALLY DEFERRED,
    CONSTRAINT TB_TA_AGO_DASHBOARD_8A2BBBEC_F
        FOREIGN KEY (DASHBOARD_ID)
        REFERENCES TB_TA_AGORA_DASHBOARD (ID)
        DEFERRABLE INITIALLY DEFERRED
);

CREATE TABLE TB_TA_AGORA_DASH_TRANSFER (
    ID VARCHAR2(32) NOT NULL PRIMARY KEY,
    TRANSFERRED_AT TIMESTAMP NOT NULL,
    DASHBOARD_ID VARCHAR2(32) NOT NULL,
    FROM_OWNER_ID VARCHAR2(32) NOT NULL,
    PREVIOUS_TRANSFER_ID VARCHAR2(32) NULL,
    TO_OWNER_ID VARCHAR2(32) NOT NULL,
    CONSTRAINT AGORA_TRANSFER_OWNERS_DIFFER CHECK (
        NOT (FROM_OWNER_ID = (TO_OWNER_ID))
    ),
    CONSTRAINT TB_TA_AGO_DASHBOARD_5AC8817B_F
        FOREIGN KEY (DASHBOARD_ID)
        REFERENCES TB_TA_AGORA_DASHBOARD (ID)
        DEFERRABLE INITIALLY DEFERRED,
    CONSTRAINT TB_TA_AGO_FROM_OWNE_B8ED8950_F
        FOREIGN KEY (FROM_OWNER_ID)
        REFERENCES TB_TA_AGORA_USER (ID)
        DEFERRABLE INITIALLY DEFERRED,
    CONSTRAINT TB_TA_AGO_PREVIOUS__96FFB1EA_F
        FOREIGN KEY (PREVIOUS_TRANSFER_ID)
        REFERENCES TB_TA_AGORA_DASH_TRANSFER (ID)
        DEFERRABLE INITIALLY DEFERRED,
    CONSTRAINT TB_TA_AGO_TO_OWNER__6BFE3D8D_F
        FOREIGN KEY (TO_OWNER_ID)
        REFERENCES TB_TA_AGORA_USER (ID)
        DEFERRABLE INITIALLY DEFERRED
);

CREATE TABLE TB_TA_AGORA_DASHBOARD_TAG (
    ID NUMBER(19) GENERATED BY DEFAULT ON NULL AS IDENTITY NOT NULL PRIMARY KEY,
    LABEL NVARCHAR2(40) NULL,
    KEY NVARCHAR2(80) NULL,
    SLOT NUMBER(11) NOT NULL CHECK (SLOT >= 0),
    CREATED_AT TIMESTAMP NOT NULL,
    DASHBOARD_ID VARCHAR2(32) NOT NULL,
    CONSTRAINT AGORA_TAG_SLOT_RANGE CHECK (
        (SLOT >= 1 AND SLOT <= 5)
    ),
    CONSTRAINT AGORA_TAG_VALUES_NOT_EMPTY CHECK (
        (NOT (LABEL IS NULL) AND NOT (KEY IS NULL))
    ),
    CONSTRAINT AGORA_TAG_DASHBOARD_KEY_UQ UNIQUE (DASHBOARD_ID, KEY),
    CONSTRAINT AGORA_TAG_DASHBOARD_SLOT_UQ UNIQUE (DASHBOARD_ID, SLOT),
    CONSTRAINT TB_TA_AGO_DASHBOARD_A389FD67_F
        FOREIGN KEY (DASHBOARD_ID)
        REFERENCES TB_TA_AGORA_DASHBOARD (ID)
        DEFERRABLE INITIALLY DEFERRED
);

CREATE TABLE TB_TA_AGORA_DASH_FAVORITE (
    ID NUMBER(19) GENERATED BY DEFAULT ON NULL AS IDENTITY NOT NULL PRIMARY KEY,
    CREATED_AT TIMESTAMP NOT NULL,
    DASHBOARD_ID VARCHAR2(32) NOT NULL,
    USER_ID VARCHAR2(32) NOT NULL,
    CONSTRAINT AGORA_FAVORITE_USER_DASH_UQ UNIQUE (USER_ID, DASHBOARD_ID),
    CONSTRAINT TB_TA_AGO_DASHBOARD_686414CA_F
        FOREIGN KEY (DASHBOARD_ID)
        REFERENCES TB_TA_AGORA_DASHBOARD (ID)
        DEFERRABLE INITIALLY DEFERRED,
    CONSTRAINT TB_TA_AGO_USER_ID_81855F3D_F
        FOREIGN KEY (USER_ID)
        REFERENCES TB_TA_AGORA_USER (ID)
        DEFERRABLE INITIALLY DEFERRED
);

CREATE TABLE TB_TA_AGORA_DASH_VIEWER_STATE (
    ID NUMBER(19) GENERATED BY DEFAULT ON NULL AS IDENTITY NOT NULL PRIMARY KEY,
    LAST_VIEWED_AT TIMESTAMP NOT NULL,
    SEEN_PUBLICATION_VERSION NUMBER(19) NOT NULL CHECK (SEEN_PUBLICATION_VERSION >= 0),
    DASHBOARD_ID VARCHAR2(32) NOT NULL,
    USER_ID VARCHAR2(32) NOT NULL,
    CONSTRAINT AGORA_VIEW_STATE_USER_DASH_UQ UNIQUE (USER_ID, DASHBOARD_ID),
    CONSTRAINT TB_TA_AGO_DASHBOARD_20C64386_F
        FOREIGN KEY (DASHBOARD_ID)
        REFERENCES TB_TA_AGORA_DASHBOARD (ID)
        DEFERRABLE INITIALLY DEFERRED,
    CONSTRAINT TB_TA_AGO_USER_ID_18799AF3_F
        FOREIGN KEY (USER_ID)
        REFERENCES TB_TA_AGORA_USER (ID)
        DEFERRABLE INITIALLY DEFERRED
);

CREATE TABLE TB_TA_AGORA_ACCESS_REQUEST (
    ID NUMBER(19) GENERATED BY DEFAULT ON NULL AS IDENTITY NOT NULL PRIMARY KEY,
    STATUS NVARCHAR2(12) NULL,
    MESSAGE NVARCHAR2(500) NULL,
    REQUESTED_AT TIMESTAMP NOT NULL,
    RESOLVED_AT TIMESTAMP NULL,
    UPDATED_AT TIMESTAMP NOT NULL,
    DASHBOARD_ID VARCHAR2(32) NOT NULL,
    REQUESTER_ID VARCHAR2(32) NOT NULL,
    RESOLVED_BY_ID VARCHAR2(32) NULL,
    CONSTRAINT AGORA_ACCESS_STATUS_VALID CHECK (
        STATUS IN ('pending', 'approved', 'denied', 'cancelled')
    ),
    CONSTRAINT AGORA_ACCESS_RESOLUTION_MATCH CHECK (
        ((RESOLVED_AT IS NULL AND RESOLVED_BY_ID IS NULL AND STATUS = 'pending') OR (NOT (STATUS =
        'pending' AND STATUS IS NOT NULL) AND RESOLVED_AT IS NOT NULL AND RESOLVED_BY_ID IS NOT
        NULL))
    ),
    CONSTRAINT AGORA_ACCESS_DASH_REQUESTER_UQ UNIQUE (DASHBOARD_ID, REQUESTER_ID),
    CONSTRAINT TB_TA_AGO_DASHBOARD_5CFCADD5_F
        FOREIGN KEY (DASHBOARD_ID)
        REFERENCES TB_TA_AGORA_DASHBOARD (ID)
        DEFERRABLE INITIALLY DEFERRED,
    CONSTRAINT TB_TA_AGO_REQUESTER_E776F594_F
        FOREIGN KEY (REQUESTER_ID)
        REFERENCES TB_TA_AGORA_USER (ID)
        DEFERRABLE INITIALLY DEFERRED,
    CONSTRAINT TB_TA_AGO_RESOLVED__E0F4DFAB_F
        FOREIGN KEY (RESOLVED_BY_ID)
        REFERENCES TB_TA_AGORA_USER (ID)
        DEFERRABLE INITIALLY DEFERRED
);

CREATE TABLE TB_TA_AGORA_ARTIFACT (
    ID VARCHAR2(32) NOT NULL PRIMARY KEY,
    KIND NVARCHAR2(4) NULL,
    LOGICAL_NAME NVARCHAR2(255) NULL,
    NAME_KEY NVARCHAR2(1024) NULL,
    STORAGE_KEY NVARCHAR2(76) NULL UNIQUE,
    BYTE_SIZE NUMBER(19) NOT NULL CHECK (BYTE_SIZE >= 0),
    MEDIA_TYPE NVARCHAR2(32) NULL,
    SHA256 NVARCHAR2(64) NULL,
    REVISION_ID VARCHAR2(32) NOT NULL,
    CONSTRAINT AGORA_ARTIFACT_NONNEGATIVE8C1F CHECK (
        BYTE_SIZE >= 0
    ),
    CONSTRAINT AGORA_ARTIFACT_SHA256_FORMAT CHECK (
        REGEXP_LIKE(SHA256, '^[0-9a-f]{64}$', 'c')
    ),
    CONSTRAINT AGORA_ARTIFACT_STORAGE_KEYB96C CHECK (
        REGEXP_LIKE(STORAGE_KEY, '^v1/[0-9a-f]{2}/[0-9a-f]{2}/[0-9a-f]{64}$', 'c')
    ),
    CONSTRAINT AGORA_ARTIFACT_NAMES_NOT_EMPTY CHECK (
        (NOT (LOGICAL_NAME IS NULL) AND NOT (NAME_KEY IS NULL))
    ),
    CONSTRAINT AGORA_ARTIFACT_REVISION_NAEE68 UNIQUE (REVISION_ID, NAME_KEY),
    CONSTRAINT AGORA_ARTIFACT_VALID_KIND CHECK (
        KIND IN ('html', 'csv', 'css', 'img', 'font')
    ),
    CONSTRAINT AGORA_ARTIFACT_KIND_MEDIA_TYPE CHECK (
        ((KIND = 'html' AND MEDIA_TYPE = 'text/html') OR (KIND = 'csv' AND MEDIA_TYPE = 'text/csv')
        OR (KIND = 'css' AND MEDIA_TYPE = 'text/css') OR (KIND = 'img' AND MEDIA_TYPE IN
        ('image/png', 'image/jpeg', 'image/gif', 'image/webp')) OR (KIND = 'font' AND MEDIA_TYPE IN
        ('font/woff', 'font/woff2')))
    ),
    CONSTRAINT TB_TA_AGO_REVISION__204A6FCA_F
        FOREIGN KEY (REVISION_ID)
        REFERENCES TB_TA_AGORA_REVISION (ID)
        DEFERRABLE INITIALLY DEFERRED,
    CONSTRAINT AGORA_ARTIFACT_STORAGE_SHARDS CHECK (
        SUBSTR(STORAGE_KEY, 4, 2) = SUBSTR(STORAGE_KEY, 10, 2) AND SUBSTR(STORAGE_KEY, 7, 2) =
        SUBSTR(STORAGE_KEY, 12, 2)
    )
);

CREATE TABLE TB_TA_AGORA_STORAGE_RESERVATION (
    ID VARCHAR2(32) NOT NULL PRIMARY KEY,
    STORAGE_KEY NVARCHAR2(76) NULL UNIQUE,
    CREATED_AT TIMESTAMP NOT NULL,
    EXPIRES_AT TIMESTAMP NOT NULL,
    VERIFIED_SIZE NUMBER(19) NULL CHECK (VERIFIED_SIZE >= 0),
    VERIFIED_SHA256 NVARCHAR2(64) NULL,
    CLEANUP_REQUIRED NUMBER(1) NOT NULL CHECK (CLEANUP_REQUIRED IN (0,1)),
    STORAGE_STATE NVARCHAR2(10) NULL,
    CONSTRAINT AGORA_RESERVATION_STORAGE_202C CHECK (
        REGEXP_LIKE(STORAGE_KEY, '^v1/[0-9a-f]{2}/[0-9a-f]{2}/[0-9a-f]{64}$', 'c')
    ),
    CONSTRAINT AGORA_RESERVATION_VERIFICA0A8E CHECK (
        ((VERIFIED_SHA256 IS NULL AND VERIFIED_SIZE IS NULL) OR (VERIFIED_SIZE IS NOT NULL AND NOT
        (VERIFIED_SHA256 IS NULL)))
    ),
    CONSTRAINT AGORA_RESERVATION_SHA256_FC2D6 CHECK (
        (VERIFIED_SHA256 IS NULL OR REGEXP_LIKE(VERIFIED_SHA256, '^[0-9a-f]{64}$', 'c'))
    ),
    CONSTRAINT AGORA_RESERVATION_VALID_STFE9A CHECK (
        STORAGE_STATE IN ('reserved', 'owned', 'collision')
    ),
    CONSTRAINT AGORA_RESERVATION_STATE_REE4D6 CHECK (
        ((STORAGE_STATE IN ('reserved', 'collision') AND VERIFIED_SHA256 IS NULL AND VERIFIED_SIZE
        IS NULL) OR (STORAGE_STATE = 'owned' AND VERIFIED_SIZE IS NOT NULL AND NOT (VERIFIED_SHA256
        IS NULL)))
    ),
    CONSTRAINT AGORA_RESERVATION_STORAGE_SHARDS CHECK (
        SUBSTR(STORAGE_KEY, 4, 2) = SUBSTR(STORAGE_KEY, 10, 2) AND SUBSTR(STORAGE_KEY, 7, 2) =
        SUBSTR(STORAGE_KEY, 12, 2)
    )
);

CREATE TABLE TB_TA_AGORA_VIEWER_GRANT (
    ID VARCHAR2(32) NOT NULL PRIMARY KEY,
    CREATED_AT TIMESTAMP NOT NULL,
    REVOKED_AT TIMESTAMP NULL,
    CREATED_BY_ID VARCHAR2(32) NOT NULL,
    DASHBOARD_ID VARCHAR2(32) NOT NULL,
    REVOKED_BY_ID VARCHAR2(32) NULL,
    VIEWER_ID VARCHAR2(32) NOT NULL,
    CONSTRAINT AGORA_GRANT_REVOCATION_FIE3B6D CHECK (
        ((REVOKED_AT IS NULL AND REVOKED_BY_ID IS NULL) OR (REVOKED_AT IS NOT NULL AND REVOKED_BY_ID
        IS NOT NULL))
    ),
    CONSTRAINT AGORA_GRANT_OWNER_NOT_VIEWER CHECK (
        NOT (VIEWER_ID = (CREATED_BY_ID))
    ),
    CONSTRAINT TB_TA_AGO_CREATED_B_978CC93D_F
        FOREIGN KEY (CREATED_BY_ID)
        REFERENCES TB_TA_AGORA_USER (ID)
        DEFERRABLE INITIALLY DEFERRED,
    CONSTRAINT TB_TA_AGO_DASHBOARD_51917667_F
        FOREIGN KEY (DASHBOARD_ID)
        REFERENCES TB_TA_AGORA_DASHBOARD (ID)
        DEFERRABLE INITIALLY DEFERRED,
    CONSTRAINT TB_TA_AGO_REVOKED_B_865780DC_F
        FOREIGN KEY (REVOKED_BY_ID)
        REFERENCES TB_TA_AGORA_USER (ID)
        DEFERRABLE INITIALLY DEFERRED,
    CONSTRAINT TB_TA_AGO_VIEWER_ID_7A1079A3_F
        FOREIGN KEY (VIEWER_ID)
        REFERENCES TB_TA_AGORA_USER (ID)
        DEFERRABLE INITIALLY DEFERRED
);

CREATE TABLE TB_TA_AGORA_LOGIN_THROTTLE (
    ID NUMBER(19) GENERATED BY DEFAULT ON NULL AS IDENTITY NOT NULL PRIMARY KEY,
    BUCKET_HASH NVARCHAR2(64) NULL UNIQUE,
    WINDOW_STARTED_AT TIMESTAMP NOT NULL,
    FAILED_ATTEMPTS NUMBER(11) NOT NULL CHECK (FAILED_ATTEMPTS >= 0),
    BLOCKED_UNTIL TIMESTAMP NULL,
    UPDATED_AT TIMESTAMP NOT NULL,
    CONSTRAINT AGORA_LOGIN_THROTTLE_HASH_64F0 CHECK (
        REGEXP_LIKE(BUCKET_HASH, '^[0-9a-f]{64}$', 'c')
    ),
    CONSTRAINT AGORA_LOGIN_THROTTLE_ATTEM84B7 CHECK (
        FAILED_ATTEMPTS >= 0
    )
);

CREATE TABLE TB_TA_AGORA_RENDER_AUTHORIZATION (
    ID VARCHAR2(32) NOT NULL PRIMARY KEY,
    TOKEN_DIGEST NVARCHAR2(64) NULL UNIQUE,
    AUDIENCE NVARCHAR2(8) NULL,
    VIEWER_AUTH_VERSION NUMBER(19) NOT NULL CHECK (VIEWER_AUTH_VERSION >= 0),
    CREATED_AT TIMESTAMP NOT NULL,
    EXPIRES_AT TIMESTAMP NOT NULL,
    REVOKED_AT TIMESTAMP NULL,
    DASHBOARD_ID VARCHAR2(32) NOT NULL,
    REVISION_ID VARCHAR2(32) NOT NULL,
    VIEWER_ID VARCHAR2(32) NOT NULL,
    VIEWER_GRANT_ID VARCHAR2(32) NULL,
    OWNER_TRANSFER_EPOCH_ID VARCHAR2(32) NULL,
    PUBLICATION_VERSION NUMBER(19) NULL CHECK (PUBLICATION_VERSION >= 0),
    AUTHORIZED_OPEN_CAPTURED_AT TIMESTAMP NULL,
    CONSTRAINT AGORA_RENDER_TOKEN_DIGEST_38A4 CHECK (
        REGEXP_LIKE(TOKEN_DIGEST, '^[0-9a-f]{64}$', 'c')
    ),
    CONSTRAINT AGORA_RENDER_AUDIENCE_VALID CHECK (
        AUDIENCE IN ('preview', 'viewer')
    ),
    CONSTRAINT AGORA_RENDER_AUTH_VERSION_9769 CHECK (
        VIEWER_AUTH_VERSION > 0
    ),
    CONSTRAINT AGORA_RENDER_EPOCH_GRANT_XOR CHECK (
        (OWNER_TRANSFER_EPOCH_ID IS NULL OR VIEWER_GRANT_ID IS NULL)
    ),
    CONSTRAINT AGORA_RENDER_PUB_VERSION_MATCH CHECK (
        ((AUDIENCE = 'preview' AND PUBLICATION_VERSION IS NULL) OR (AUDIENCE = 'viewer' AND
        PUBLICATION_VERSION > 0 AND PUBLICATION_VERSION IS NOT NULL))
    ),
    CONSTRAINT TB_TA_AGO_DASHBOARD_D43031B9_F
        FOREIGN KEY (DASHBOARD_ID)
        REFERENCES TB_TA_AGORA_DASHBOARD (ID)
        DEFERRABLE INITIALLY DEFERRED,
    CONSTRAINT TB_TA_AGO_REVISION__4833DC2C_F
        FOREIGN KEY (REVISION_ID)
        REFERENCES TB_TA_AGORA_REVISION (ID)
        DEFERRABLE INITIALLY DEFERRED,
    CONSTRAINT TB_TA_AGO_VIEWER_ID_2EADE781_F
        FOREIGN KEY (VIEWER_ID)
        REFERENCES TB_TA_AGORA_USER (ID)
        DEFERRABLE INITIALLY DEFERRED,
    CONSTRAINT TB_TA_AGO_VIEWER_GR_262BF900_F
        FOREIGN KEY (VIEWER_GRANT_ID)
        REFERENCES TB_TA_AGORA_VIEWER_GRANT (ID)
        DEFERRABLE INITIALLY DEFERRED,
    CONSTRAINT TB_TA_AGO_OWNER_TRA_0C7C5C3A_F
        FOREIGN KEY (OWNER_TRANSFER_EPOCH_ID)
        REFERENCES TB_TA_AGORA_DASH_TRANSFER (ID)
        DEFERRABLE INITIALLY DEFERRED
);

CREATE TABLE TB_TA_AGORA_AUTHORIZED_OPEN (
    ID NUMBER(19) GENERATED BY DEFAULT ON NULL AS IDENTITY NOT NULL PRIMARY KEY,
    PUBLICATION_VERSION NUMBER(19) NOT NULL CHECK (PUBLICATION_VERSION >= 0),
    OPENED_AT TIMESTAMP NOT NULL,
    AGGREGATED_AT TIMESTAMP NULL,
    DASHBOARD_ID VARCHAR2(32) NOT NULL,
    REVISION_ID VARCHAR2(32) NOT NULL,
    SOURCE_AUTHORIZATION_ID VARCHAR2(32) NOT NULL UNIQUE,
    VIEWER_ID VARCHAR2(32) NOT NULL,
    CONSTRAINT AGORA_OPEN_PUB_VERSION_POS CHECK (
        PUBLICATION_VERSION > 0
    ),
    CONSTRAINT TB_TA_AGO_DASHBOARD_1BFED781_F
        FOREIGN KEY (DASHBOARD_ID)
        REFERENCES TB_TA_AGORA_DASHBOARD (ID)
        DEFERRABLE INITIALLY DEFERRED,
    CONSTRAINT TB_TA_AGO_REVISION__B4DBDD75_F
        FOREIGN KEY (REVISION_ID)
        REFERENCES TB_TA_AGORA_REVISION (ID)
        DEFERRABLE INITIALLY DEFERRED,
    CONSTRAINT TB_TA_AGO_SOURCE_AU_D894BD11_F
        FOREIGN KEY (SOURCE_AUTHORIZATION_ID)
        REFERENCES TB_TA_AGORA_RENDER_AUTHORIZATION (ID)
        DEFERRABLE INITIALLY DEFERRED,
    CONSTRAINT TB_TA_AGO_VIEWER_ID_79F4630D_F
        FOREIGN KEY (VIEWER_ID)
        REFERENCES TB_TA_AGORA_USER (ID)
        DEFERRABLE INITIALLY DEFERRED
);

CREATE TABLE TB_TA_AGORA_OPEN_DAILY (
    ID NUMBER(19) GENERATED BY DEFAULT ON NULL AS IDENTITY NOT NULL PRIMARY KEY,
    DAY DATE NOT NULL,
    AUTHORIZED_OPEN_COUNT NUMBER(19) NOT NULL CHECK (AUTHORIZED_OPEN_COUNT >= 0),
    DASHBOARD_ID VARCHAR2(32) NOT NULL,
    CONSTRAINT AGORA_OPEN_DAILY_DASH_DAY_UQ UNIQUE (DASHBOARD_ID, DAY),
    CONSTRAINT TB_TA_AGO_DASHBOARD_91DDFE24_F
        FOREIGN KEY (DASHBOARD_ID)
        REFERENCES TB_TA_AGORA_DASHBOARD (ID)
        DEFERRABLE INITIALLY DEFERRED
);

CREATE TABLE TB_TA_AGORA_VIEWER_OPEN_SUM (
    ID NUMBER(19) GENERATED BY DEFAULT ON NULL AS IDENTITY NOT NULL PRIMARY KEY,
    AUTHORIZED_OPEN_COUNT NUMBER(19) NOT NULL CHECK (AUTHORIZED_OPEN_COUNT >= 0),
    FIRST_OPENED_AT TIMESTAMP NOT NULL,
    LAST_OPENED_AT TIMESTAMP NOT NULL,
    DASHBOARD_ID VARCHAR2(32) NOT NULL,
    VIEWER_ID VARCHAR2(32) NOT NULL,
    CONSTRAINT AGORA_VIEW_SUM_DASH_VIEWER_UQ UNIQUE (DASHBOARD_ID, VIEWER_ID),
    CONSTRAINT AGORA_VIEW_SUM_TIME_ORDER CHECK (
        LAST_OPENED_AT >= (FIRST_OPENED_AT)
    ),
    CONSTRAINT TB_TA_AGO_DASHBOARD_3DAD6FFE_F
        FOREIGN KEY (DASHBOARD_ID)
        REFERENCES TB_TA_AGORA_DASHBOARD (ID)
        DEFERRABLE INITIALLY DEFERRED,
    CONSTRAINT TB_TA_AGO_VIEWER_ID_24D3CE9F_F
        FOREIGN KEY (VIEWER_ID)
        REFERENCES TB_TA_AGORA_USER (ID)
        DEFERRABLE INITIALLY DEFERRED
);

CREATE TABLE TB_TA_AGORA_OPEN_SNAPSHOT (
    ID NUMBER(19) GENERATED BY DEFAULT ON NULL AS IDENTITY NOT NULL PRIMARY KEY,
    AUTHORIZED_OPEN_COUNT NUMBER(19) NOT NULL CHECK (AUTHORIZED_OPEN_COUNT >= 0),
    LAST_OPENED_AT TIMESTAMP NOT NULL,
    CAPTURED_THROUGH_OPEN_ID NUMBER(19) NOT NULL CHECK (CAPTURED_THROUGH_OPEN_ID >= 0),
    UPDATED_AT TIMESTAMP NOT NULL,
    DASHBOARD_ID VARCHAR2(32) NOT NULL UNIQUE,
    CONSTRAINT TB_TA_AGO_DASHBOARD_0C474914_F
        FOREIGN KEY (DASHBOARD_ID)
        REFERENCES TB_TA_AGORA_DASHBOARD (ID)
        DEFERRABLE INITIALLY DEFERRED
);

CREATE TABLE TB_TA_AGORA_ANALYTICS_CKPT (
    PIPELINE_KEY NVARCHAR2(32) NOT NULL PRIMARY KEY,
    LAST_COMPLETED_OPEN_ID NUMBER(19) NOT NULL CHECK (LAST_COMPLETED_OPEN_ID >= 0),
    UPDATED_AT TIMESTAMP NOT NULL,
    CONSTRAINT AGORA_ANALYTICS_CKPT_KEY CHECK (
        PIPELINE_KEY = 'authorized_opens_v1'
    )
);

CREATE TABLE TB_TA_AGORA_AUDIT_EVENT (
    ID NUMBER(19) GENERATED BY DEFAULT ON NULL AS IDENTITY NOT NULL PRIMARY KEY,
    EVENT_TYPE NVARCHAR2(64) NULL,
    OCCURRED_AT TIMESTAMP NOT NULL,
    REQUEST_ID VARCHAR2(32) NULL,
    METADATA NCLOB NOT NULL CHECK (METADATA IS JSON),
    ACTOR_ID VARCHAR2(32) NULL,
    TARGET_USER_ID VARCHAR2(32) NULL,
    DASHBOARD_ID VARCHAR2(32) NULL,
    REVISION_ID VARCHAR2(32) NULL,
    CONSTRAINT AGORA_AUDIT_EVENT_TYPE_FORMAT CHECK (
        REGEXP_LIKE(EVENT_TYPE, '^[a-z][a-z0-9_.-]{2,63}$', 'c')
    ),
    CONSTRAINT TB_TA_AGO_ACTOR_ID_D78ABC0C_F
        FOREIGN KEY (ACTOR_ID)
        REFERENCES TB_TA_AGORA_USER (ID)
        DEFERRABLE INITIALLY DEFERRED,
    CONSTRAINT TB_TA_AGO_TARGET_US_1D8FDD46_F
        FOREIGN KEY (TARGET_USER_ID)
        REFERENCES TB_TA_AGORA_USER (ID)
        DEFERRABLE INITIALLY DEFERRED,
    CONSTRAINT TB_TA_AGO_DASHBOARD_B161C04F_F
        FOREIGN KEY (DASHBOARD_ID)
        REFERENCES TB_TA_AGORA_DASHBOARD (ID)
        DEFERRABLE INITIALLY DEFERRED,
    CONSTRAINT TB_TA_AGO_REVISION__41580B77_F
        FOREIGN KEY (REVISION_ID)
        REFERENCES TB_TA_AGORA_REVISION (ID)
        DEFERRABLE INITIALLY DEFERRED
);

-- Django framework tables

CREATE TABLE TB_TA_AGORA_DJANGO_CONTENT_TYPE (
    ID NUMBER(11) GENERATED BY DEFAULT ON NULL AS IDENTITY NOT NULL PRIMARY KEY,
    APP_LABEL NVARCHAR2(100) NULL,
    MODEL NVARCHAR2(100) NULL,
    CONSTRAINT TB_TA_AGO_APP_LABEL_99F8C622_U UNIQUE (APP_LABEL, MODEL)
);

CREATE TABLE TB_TA_AGORA_AUTH_PERMISSION (
    ID NUMBER(11) GENERATED BY DEFAULT ON NULL AS IDENTITY NOT NULL PRIMARY KEY,
    NAME NVARCHAR2(255) NULL,
    CONTENT_TYPE_ID NUMBER(11) NOT NULL,
    CODENAME NVARCHAR2(100) NULL,
    CONSTRAINT TB_TA_AGO_CONTENT_T_AA5A8101_U UNIQUE (CONTENT_TYPE_ID, CODENAME),
    CONSTRAINT TB_TA_AGO_CONTENT_T_0FD891A5_F
        FOREIGN KEY (CONTENT_TYPE_ID)
        REFERENCES TB_TA_AGORA_DJANGO_CONTENT_TYPE (ID)
        DEFERRABLE INITIALLY DEFERRED
);

CREATE TABLE TB_TA_AGORA_AUTH_GROUP (
    ID NUMBER(11) GENERATED BY DEFAULT ON NULL AS IDENTITY NOT NULL PRIMARY KEY,
    NAME NVARCHAR2(150) NULL UNIQUE
);

CREATE TABLE TB_TA_AGORA_AUTH_GROUP_PERMISSIONS (
    ID NUMBER(19) GENERATED BY DEFAULT ON NULL AS IDENTITY NOT NULL PRIMARY KEY,
    GROUP_ID NUMBER(11) NOT NULL,
    PERMISSION_ID NUMBER(11) NOT NULL,
    CONSTRAINT TB_TA_AGO_GROUP_ID__A1440A4D_U UNIQUE (GROUP_ID, PERMISSION_ID),
    CONSTRAINT TB_TA_AGO_GROUP_ID_1C9117B6_F
        FOREIGN KEY (GROUP_ID)
        REFERENCES TB_TA_AGORA_AUTH_GROUP (ID)
        DEFERRABLE INITIALLY DEFERRED,
    CONSTRAINT TB_TA_AGO_PERMISSIO_09298595_F
        FOREIGN KEY (PERMISSION_ID)
        REFERENCES TB_TA_AGORA_AUTH_PERMISSION (ID)
        DEFERRABLE INITIALLY DEFERRED
);

CREATE TABLE TB_TA_AGORA_DJANGO_SESSION (
    SESSION_KEY NVARCHAR2(40) NOT NULL PRIMARY KEY,
    SESSION_DATA NCLOB NULL,
    EXPIRE_DATE TIMESTAMP NOT NULL
);

CREATE TABLE TB_TA_AGORA_DJANGO_MIGRATIONS (
    ID NUMBER(19) GENERATED BY DEFAULT ON NULL AS IDENTITY NOT NULL PRIMARY KEY,
    APP NVARCHAR2(255) NULL,
    NAME NVARCHAR2(255) NULL,
    APPLIED TIMESTAMP NOT NULL
);

-- Cyclic foreign keys

ALTER TABLE TB_TA_AGORA_DASHBOARD
    ADD CONSTRAINT TB_TA_AGO_LATEST_RE_5CBC8DA3_F
    FOREIGN KEY (LATEST_REVISION_ID)
    REFERENCES TB_TA_AGORA_REVISION (ID) DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE TB_TA_AGORA_DASHBOARD
    ADD CONSTRAINT TB_TA_AGO_PUBLISHED_F6DC994F_F
    FOREIGN KEY (PUBLISHED_REVISION_ID)
    REFERENCES TB_TA_AGORA_REVISION (ID) DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE TB_TA_AGORA_DASHBOARD
    ADD CONSTRAINT TB_TA_AGO_LAST_OWNE_C15EDFD1_F
    FOREIGN KEY (LAST_OWNERSHIP_TRANSFER_ID)
    REFERENCES TB_TA_AGORA_DASH_TRANSFER (ID) DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE TB_TA_AGORA_DASHBOARD
    ADD CONSTRAINT AGORA_DASH_LATEST_OWNED_FK
    FOREIGN KEY (ID, LATEST_REVISION_ID)
    REFERENCES TB_TA_AGORA_REVISION (DASHBOARD_ID, ID) DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE TB_TA_AGORA_DASHBOARD
    ADD CONSTRAINT AGORA_DASH_PUBLISHED_OWNED_FK
    FOREIGN KEY (ID, PUBLISHED_REVISION_ID)
    REFERENCES TB_TA_AGORA_REVISION (DASHBOARD_ID, ID) DEFERRABLE INITIALLY DEFERRED;

-- Indexes

CREATE INDEX TB_TA_AGOR_CONTENT_TY_0FD891A5 ON TB_TA_AGORA_AUTH_PERMISSION (CONTENT_TYPE_ID);

CREATE INDEX TB_TA_AGOR_GROUP_ID_1C9117B6 ON TB_TA_AGORA_AUTH_GROUP_PERMISSIONS (GROUP_ID);

CREATE INDEX TB_TA_AGOR_PERMISSION_09298595 ON TB_TA_AGORA_AUTH_GROUP_PERMISSIONS (PERMISSION_ID);

CREATE INDEX TB_TA_AGOR_OWNER_ID_A3F88D8D ON TB_TA_AGORA_DASHBOARD (OWNER_ID);

CREATE INDEX TB_TA_AGOR_LATEST_REV_5CBC8DA3 ON TB_TA_AGORA_DASHBOARD (LATEST_REVISION_ID);

CREATE INDEX TB_TA_AGOR_PUBLISHED__F6DC994F ON TB_TA_AGORA_DASHBOARD (PUBLISHED_REVISION_ID);

CREATE INDEX AGORA_DASH_OWNER_STATE_IDX ON TB_TA_AGORA_DASHBOARD (OWNER_ID, STATE);

CREATE INDEX AGORA_DASH_STATE_UPDATED_IDX ON TB_TA_AGORA_DASHBOARD (STATE, UPDATED_AT);

CREATE INDEX AGORA_DASH_OWNER_STALE_IDX ON TB_TA_AGORA_DASHBOARD (OWNER_ID, STALE_AFTER, ID);

CREATE INDEX AGORA_DASH_STALE_SCAN_IDX ON TB_TA_AGORA_DASHBOARD (STALE_AFTER, ID);

CREATE INDEX TB_TA_AGOR_CREATED_BY_CC846DF3 ON TB_TA_AGORA_REVISION (CREATED_BY_ID);

CREATE INDEX TB_TA_AGOR_DASHBOARD__8A2BBBEC ON TB_TA_AGORA_REVISION (DASHBOARD_ID);

CREATE INDEX TB_TA_AGOR_ACTOR_ID_D78ABC0C ON TB_TA_AGORA_AUDIT_EVENT (ACTOR_ID);

CREATE INDEX TB_TA_AGOR_TARGET_USE_1D8FDD46 ON TB_TA_AGORA_AUDIT_EVENT (TARGET_USER_ID);

CREATE INDEX TB_TA_AGOR_DASHBOARD__B161C04F ON TB_TA_AGORA_AUDIT_EVENT (DASHBOARD_ID);

CREATE INDEX TB_TA_AGOR_REVISION_I_41580B77 ON TB_TA_AGORA_AUDIT_EVENT (REVISION_ID);

CREATE INDEX AGORA_AUDIT_DASH_TIME_IDX ON TB_TA_AGORA_AUDIT_EVENT (DASHBOARD_ID, OCCURRED_AT, ID);

CREATE INDEX AGORA_AUDIT_ACTOR_TIME_IDX ON TB_TA_AGORA_AUDIT_EVENT (ACTOR_ID, OCCURRED_AT, ID);

CREATE INDEX AGORA_AUDIT_TYPE_TIME_IDX ON TB_TA_AGORA_AUDIT_EVENT (EVENT_TYPE, OCCURRED_AT);

CREATE INDEX TB_TA_AGOR_REVISION_I_204A6FCA ON TB_TA_AGORA_ARTIFACT (REVISION_ID);

CREATE INDEX AGORA_ART_REV_KIND_IDX ON TB_TA_AGORA_ARTIFACT (REVISION_ID, KIND);

CREATE INDEX AGORA_RES_CLEANUP_EXPIRY_IDX
    ON TB_TA_AGORA_STORAGE_RESERVATION (
        CLEANUP_REQUIRED,
        EXPIRES_AT
    );

CREATE INDEX TB_TA_AGOR_CREATED_BY_978CC93D ON TB_TA_AGORA_VIEWER_GRANT (CREATED_BY_ID);

CREATE INDEX TB_TA_AGOR_DASHBOARD__51917667 ON TB_TA_AGORA_VIEWER_GRANT (DASHBOARD_ID);

CREATE INDEX TB_TA_AGOR_REVOKED_BY_865780DC ON TB_TA_AGORA_VIEWER_GRANT (REVOKED_BY_ID);

CREATE INDEX TB_TA_AGOR_VIEWER_ID_7A1079A3 ON TB_TA_AGORA_VIEWER_GRANT (VIEWER_ID);

CREATE INDEX AGORA_GRANT_DASH_ACTIVE_IDX ON TB_TA_AGORA_VIEWER_GRANT (DASHBOARD_ID, REVOKED_AT);

CREATE INDEX AGORA_GRANT_SCOPE_ACTIVE_IDX
    ON TB_TA_AGORA_VIEWER_GRANT (
        DASHBOARD_ID,
        VIEWER_ID,
        REVOKED_AT
    );

CREATE INDEX AGORA_GRANT_VIEWER_ACTIVE_IDX
    ON TB_TA_AGORA_VIEWER_GRANT (
        VIEWER_ID,
        REVOKED_AT,
        CREATED_AT DESC,
        ID DESC
    );

CREATE INDEX AGORA_AUTH_THROTTLE_UPD_IDX ON TB_TA_AGORA_LOGIN_THROTTLE (UPDATED_AT);

CREATE INDEX TB_TA_AGOR_DASHBOARD__D43031B9 ON TB_TA_AGORA_RENDER_AUTHORIZATION (DASHBOARD_ID);

CREATE INDEX TB_TA_AGOR_REVISION_I_4833DC2C ON TB_TA_AGORA_RENDER_AUTHORIZATION (REVISION_ID);

CREATE INDEX TB_TA_AGOR_VIEWER_ID_2EADE781 ON TB_TA_AGORA_RENDER_AUTHORIZATION (VIEWER_ID);

CREATE INDEX TB_TA_AGOR_VIEWER_GRA_262BF900 ON TB_TA_AGORA_RENDER_AUTHORIZATION (VIEWER_GRANT_ID);

CREATE INDEX TB_TA_AGOR_OWNER_TRAN_0C7C5C3A
    ON TB_TA_AGORA_RENDER_AUTHORIZATION (
        OWNER_TRANSFER_EPOCH_ID
    );

CREATE INDEX AGORA_RENDER_EXPIRY_IDX ON TB_TA_AGORA_RENDER_AUTHORIZATION (EXPIRES_AT);

CREATE INDEX AGORA_RENDER_SCOPE_IDX
    ON TB_TA_AGORA_RENDER_AUTHORIZATION (
        DASHBOARD_ID,
        VIEWER_ID,
        AUDIENCE
    );

CREATE INDEX TB_TA_AGOR_DASHBOARD__A389FD67 ON TB_TA_AGORA_DASHBOARD_TAG (DASHBOARD_ID);

CREATE INDEX AGORA_TAG_LOOKUP_IDX ON TB_TA_AGORA_DASHBOARD_TAG (KEY, DASHBOARD_ID);

CREATE INDEX TB_TA_AGOR_DASHBOARD__686414CA ON TB_TA_AGORA_DASH_FAVORITE (DASHBOARD_ID);

CREATE INDEX TB_TA_AGOR_USER_ID_81855F3D ON TB_TA_AGORA_DASH_FAVORITE (USER_ID);

CREATE INDEX AGORA_FAVORITE_RECENT_IDX
    ON TB_TA_AGORA_DASH_FAVORITE (
        USER_ID,
        CREATED_AT DESC,
        ID DESC
    );

CREATE INDEX TB_TA_AGOR_DASHBOARD__20C64386 ON TB_TA_AGORA_DASH_VIEWER_STATE (DASHBOARD_ID);

CREATE INDEX TB_TA_AGOR_USER_ID_18799AF3 ON TB_TA_AGORA_DASH_VIEWER_STATE (USER_ID);

CREATE INDEX AGORA_VIEW_STATE_RECENT_IDX
    ON TB_TA_AGORA_DASH_VIEWER_STATE (
        USER_ID,
        LAST_VIEWED_AT DESC,
        ID DESC
    );

CREATE INDEX TB_TA_AGOR_DASHBOARD__5CFCADD5 ON TB_TA_AGORA_ACCESS_REQUEST (DASHBOARD_ID);

CREATE INDEX TB_TA_AGOR_REQUESTER__E776F594 ON TB_TA_AGORA_ACCESS_REQUEST (REQUESTER_ID);

CREATE INDEX TB_TA_AGOR_RESOLVED_B_E0F4DFAB ON TB_TA_AGORA_ACCESS_REQUEST (RESOLVED_BY_ID);

CREATE INDEX AGORA_ACCESS_OWNER_QUEUE_IDX
    ON TB_TA_AGORA_ACCESS_REQUEST (
        DASHBOARD_ID,
        STATUS,
        REQUESTED_AT DESC,
        ID DESC
    );

CREATE INDEX TB_TA_AGOR_DASHBOARD__5AC8817B ON TB_TA_AGORA_DASH_TRANSFER (DASHBOARD_ID);

CREATE INDEX TB_TA_AGOR_FROM_OWNER_B8ED8950 ON TB_TA_AGORA_DASH_TRANSFER (FROM_OWNER_ID);

CREATE INDEX TB_TA_AGOR_PREVIOUS_T_96FFB1EA ON TB_TA_AGORA_DASH_TRANSFER (PREVIOUS_TRANSFER_ID);

CREATE INDEX TB_TA_AGOR_TO_OWNER_I_6BFE3D8D ON TB_TA_AGORA_DASH_TRANSFER (TO_OWNER_ID);

CREATE INDEX AGORA_TRANSFER_HISTORY_IDX
    ON TB_TA_AGORA_DASH_TRANSFER (
        DASHBOARD_ID,
        TRANSFERRED_AT DESC,
        ID
    );

CREATE INDEX TB_TA_AGOR_DASHBOARD__1BFED781 ON TB_TA_AGORA_AUTHORIZED_OPEN (DASHBOARD_ID);

CREATE INDEX TB_TA_AGOR_REVISION_I_B4DBDD75 ON TB_TA_AGORA_AUTHORIZED_OPEN (REVISION_ID);

CREATE INDEX TB_TA_AGOR_VIEWER_ID_79F4630D ON TB_TA_AGORA_AUTHORIZED_OPEN (VIEWER_ID);

CREATE INDEX AGORA_OPEN_PENDING_IDX ON TB_TA_AGORA_AUTHORIZED_OPEN (AGGREGATED_AT, OPENED_AT, ID);

CREATE INDEX AGORA_OPEN_RETENTION_IDX ON TB_TA_AGORA_AUTHORIZED_OPEN (OPENED_AT, ID);

CREATE INDEX TB_TA_AGOR_DASHBOARD__91DDFE24 ON TB_TA_AGORA_OPEN_DAILY (DASHBOARD_ID);

CREATE INDEX AGORA_OPEN_DAILY_READ_IDX ON TB_TA_AGORA_OPEN_DAILY (DASHBOARD_ID, DAY DESC, ID DESC);

CREATE INDEX TB_TA_AGOR_DASHBOARD__3DAD6FFE ON TB_TA_AGORA_VIEWER_OPEN_SUM (DASHBOARD_ID);

CREATE INDEX TB_TA_AGOR_VIEWER_ID_24D3CE9F ON TB_TA_AGORA_VIEWER_OPEN_SUM (VIEWER_ID);

CREATE INDEX AGORA_VIEW_SUM_RANK_IDX
    ON TB_TA_AGORA_VIEWER_OPEN_SUM (
        DASHBOARD_ID,
        AUTHORIZED_OPEN_COUNT DESC,
        VIEWER_ID
    );

CREATE INDEX AGORA_OPEN_SNAPSHOT_RANK_IDX
    ON TB_TA_AGORA_OPEN_SNAPSHOT (
        AUTHORIZED_OPEN_COUNT DESC,
        DASHBOARD_ID
    );

CREATE INDEX TB_TA_AGOR_EXPIRE_DAT_C4E5A16B ON TB_TA_AGORA_DJANGO_SESSION (EXPIRE_DATE);

CREATE UNIQUE INDEX AGORA_ARTIFACT_ONE_HTML_IDX
    ON TB_TA_AGORA_ARTIFACT (
        CASE WHEN KIND = 'html' THEN REVISION_ID ELSE NULL END
    );

CREATE UNIQUE INDEX AGORA_GRANT_ACTIVE_UQ_IDX
    ON TB_TA_AGORA_VIEWER_GRANT (
        CASE WHEN REVOKED_AT IS NULL THEN DASHBOARD_ID ELSE NULL END,
        CASE WHEN REVOKED_AT IS NULL THEN VIEWER_ID ELSE NULL END
    );

CREATE UNIQUE INDEX AGORA_TRANSFER_CHAIN_UQ_IDX
    ON TB_TA_AGORA_DASH_TRANSFER (
        DASHBOARD_ID,
        NVL(PREVIOUS_TRANSFER_ID, HEXTORAW('00000000000000000000000000000000'))
    );
