"""Offline contract checks for the generated Oracle schema artifact."""

from __future__ import annotations

import os
import re
import subprocess
from pathlib import Path
from types import SimpleNamespace

import pytest

from scripts import generate_oracle_schema
from scripts.generate_oracle_schema import render_schema

_ROOT = Path(__file__).resolve().parents[1]
_SCHEMA = _ROOT / "database" / "oracle" / "schema.sql"
_GENERATOR = _ROOT / "scripts" / "generate_oracle_schema.py"


def _executable_lines(sql: str) -> str:
    return "\n".join(line for line in sql.splitlines() if not line.lstrip().startswith("--"))


def test_checked_in_artifact_matches_deterministic_generation() -> None:
    assert _SCHEMA.read_text(encoding="utf-8") == render_schema()


def test_generation_uses_the_oracle_backend_without_opening_a_connection(
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    from agora.db.backends.treasury_oracle.base import DatabaseWrapper

    def fail_if_connected(*_args: object, **_kwargs: object) -> object:
        raise AssertionError("offline schema generation attempted an Oracle connection")

    monkeypatch.setattr(DatabaseWrapper, "get_new_connection", fail_if_connected)
    generated = render_schema()
    assert 'CREATE TABLE "TB_TA_AGORA_USER"' in generated
    assert "GENERATED BY DEFAULT ON NULL AS IDENTITY" in generated


def test_generation_does_not_leak_environment_on_success_or_failure(
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    before = dict(os.environ)
    render_schema()
    assert dict(os.environ) == before

    def fail_after_setup(*_args: object, **_kwargs: object) -> object:
        raise RuntimeError("synthetic schema-generation failure")

    monkeypatch.setattr(generate_oracle_schema, "_collect_raw_sql", fail_after_setup)
    with pytest.raises(RuntimeError, match="synthetic schema-generation failure"):
        render_schema()
    assert dict(os.environ) == before


def test_artifact_contains_all_final_agora_and_framework_tables() -> None:
    sql = _executable_lines(_SCHEMA.read_text(encoding="utf-8"))
    expected_tables = {
        "TB_TA_AGORA_USER",
        "TB_TA_AGORA_DASHBOARD",
        "TB_TA_AGORA_REVISION",
        "TB_TA_AGORA_AUDIT_EVENT",
        "TB_TA_AGORA_ARTIFACT",
        "TB_TA_AGORA_STORAGE_RESERVATION",
        "TB_TA_AGORA_VIEWER_GRANT",
        "TB_TA_AGORA_LOGIN_THROTTLE",
        "TB_TA_AGORA_RENDER_AUTHORIZATION",
        "TB_TA_AGORA_DASHBOARD_TAG",
        "TB_TA_AGORA_DASH_FAVORITE",
        "TB_TA_AGORA_DASH_VIEWER_STATE",
        "TB_TA_AGORA_ACCESS_REQUEST",
        "TB_TA_AGORA_DASH_TRANSFER",
        "TB_TA_AGORA_AUTHORIZED_OPEN",
        "TB_TA_AGORA_OPEN_DAILY",
        "TB_TA_AGORA_VIEWER_OPEN_SUM",
        "TB_TA_AGORA_OPEN_SNAPSHOT",
        "TB_TA_AGORA_ANALYTICS_CKPT",
        "TB_TA_AGORA_AUTH_PERMISSION",
        "TB_TA_AGORA_AUTH_GROUP",
        "TB_TA_AGORA_AUTH_GROUP_PERMISSIONS",
        "TB_TA_AGORA_DJANGO_CONTENT_TYPE",
        "TB_TA_AGORA_DJANGO_SESSION",
        "TB_TA_AGORA_DJANGO_MIGRATIONS",
    }
    actual_table_targets = re.findall(r'CREATE TABLE "([A-Z0-9_$#]+)"', sql)
    assert len(expected_tables) == 25
    assert len(actual_table_targets) == 25
    assert len(set(actual_table_targets)) == 25
    assert set(actual_table_targets) == expected_tables


def test_artifact_carries_forward_migration_owned_oracle_objects() -> None:
    sql = _executable_lines(_SCHEMA.read_text(encoding="utf-8")).upper()
    expected_indexes = {
        "AGORA_ARTIFACT_ONE_HTML_IDX",
        "AGORA_GRANT_ACTIVE_UQ_IDX",
        "AGORA_TRANSFER_CHAIN_UQ_IDX",
    }
    expected_constraints = {
        "AGORA_ARTIFACT_STORAGE_SHARDS",
        "AGORA_RESERVATION_STORAGE_SHARDS",
        "AGORA_DASH_LATEST_OWNED_FK",
        "AGORA_DASH_PUBLISHED_OWNED_FK",
    }
    expected_triggers = {
        "AGORA_USER_RETENTION_GUARD",
        "AGORA_USER_AUTH_VERSION_GUARD",
        "AGORA_DASHBOARD_GUARD",
        "AGORA_DASH_META_GUARD",
        "AGORA_VIEW_STATE_GUARD",
        "AGORA_ACCESS_REQUEST_GUARD",
        "AGORA_REVISION_IMMUT_GUARD",
        "AGORA_REVISION_COMPLETE_GUARD",
        "AGORA_REVISION_AUTH_GUARD",
        "AGORA_ARTIFACT_INSERT_GUARD",
        "AGORA_ARTIFACT_IMMUT_GUARD",
        "AGORA_RESERVATION_MUT_GUARD",
        "AGORA_GRANT_IMMUT_GUARD",
        "AGORA_AUDIT_APPEND_GUARD",
        "AGORA_DASHBOARD_LATEST_GUARD",
        "AGORA_AUTH_OPEN_GUARD",
        "AGORA_AUTH_OPEN_MARK",
        "AGORA_RENDER_OPEN_GUARD",
        "AGORA_ANALYTICS_CKPT_GUARD",
        "AGORA_TRANSFER_HISTORY_GUARD",
    }
    actual_indexes = {
        name
        for name in re.findall(r"CREATE UNIQUE INDEX\s+([A-Z0-9_$#]+)\b", sql)
        if name in expected_indexes
    }
    actual_constraints = {
        name
        for name in re.findall(r"ADD CONSTRAINT\s+([A-Z0-9_$#]+)\b", sql)
        if name in expected_constraints
    }
    actual_triggers = set(re.findall(r"CREATE OR REPLACE TRIGGER\s+([A-Z0-9_$#]+)\b", sql))
    assert actual_indexes == expected_indexes
    assert actual_constraints == expected_constraints
    assert actual_triggers == expected_triggers


def test_artifact_has_no_legacy_table_identifiers_in_executable_sql() -> None:
    sql = _executable_lines(_SCHEMA.read_text(encoding="utf-8")).upper()
    assert "PERSISTENCE_" not in sql
    assert not re.search(
        r"\b(?:CREATE TABLE|ALTER TABLE|ON|REFERENCES)\s+\"?TB_TA_(?!AGORA_)[A-Z0-9_$#]+",
        sql,
    )


def test_artifact_is_utf8_lf_and_defers_foreign_keys_after_tables() -> None:
    artifact = _SCHEMA.read_bytes()
    assert b"\r" not in artifact
    assert artifact.startswith(b"-- Agora Oracle schema artifact")

    sql = artifact.decode("utf-8")
    last_create_table = sql.rfind("CREATE TABLE ")
    first_foreign_key = sql.find(" FOREIGN KEY ")
    assert last_create_table >= 0
    assert first_foreign_key > last_create_table
    assert sql.count(" FOREIGN KEY ") == 45
    assert len(re.findall(r"(?im)^CREATE (?:UNIQUE )?INDEX ", sql)) == 69


def test_identity_tables_match_django_oracle_backend_behavior() -> None:
    sql = _executable_lines(_SCHEMA.read_text(encoding="utf-8")).upper()
    actual = {
        match.group(1)
        for match in re.finditer(
            r'CREATE TABLE "([A-Z0-9_$#]+)" \([^;]*GENERATED BY DEFAULT ON NULL AS IDENTITY',
            sql,
        )
    }
    expected = {
        "TB_TA_AGORA_AUTH_PERMISSION",
        "TB_TA_AGORA_AUTH_GROUP",
        "TB_TA_AGORA_AUTH_GROUP_PERMISSIONS",
        "TB_TA_AGORA_DJANGO_CONTENT_TYPE",
        "TB_TA_AGORA_AUDIT_EVENT",
        "TB_TA_AGORA_LOGIN_THROTTLE",
        "TB_TA_AGORA_DASHBOARD_TAG",
        "TB_TA_AGORA_DASH_FAVORITE",
        "TB_TA_AGORA_DASH_VIEWER_STATE",
        "TB_TA_AGORA_ACCESS_REQUEST",
        "TB_TA_AGORA_AUTHORIZED_OPEN",
        "TB_TA_AGORA_OPEN_DAILY",
        "TB_TA_AGORA_VIEWER_OPEN_SUM",
        "TB_TA_AGORA_OPEN_SNAPSHOT",
        "TB_TA_AGORA_DJANGO_MIGRATIONS",
    }
    assert len(expected) == 15
    assert actual == expected


def test_known_migration_objects_have_no_duplicate_names() -> None:
    sql = _executable_lines(_SCHEMA.read_text(encoding="utf-8")).upper()
    names = re.findall(
        r'(?:CREATE OR REPLACE TRIGGER|CREATE(?: UNIQUE)? INDEX|ADD CONSTRAINT|CONSTRAINT)\s+"?'
        r'([A-Z0-9_$#]+)"?',
        sql,
    )
    assert len(names) == len(set(names))


def test_render_restores_wrapper_recorder_and_runtime_model_metadata(
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    from django.contrib.auth.models import Group
    from django.db import connections
    from django.db.migrations.recorder import MigrationRecorder

    connection = connections["default"]
    operators_sentinel = object()
    pattern_ops_sentinel = object()
    monkeypatch.setitem(connection.__dict__, "operators", operators_sentinel)
    monkeypatch.setitem(connection.__dict__, "pattern_ops", pattern_ops_sentinel)
    wrapper_before = {
        name: (name in connection.__dict__, connection.__dict__.get(name))
        for name in ("operators", "pattern_ops")
    }
    recorder_before = MigrationRecorder.Migration._meta.db_table
    runtime_through = Group.permissions.through
    runtime_through_before = runtime_through._meta.db_table
    environment_before = dict(os.environ)

    render_schema()
    render_schema()

    def assert_restored() -> None:
        for name, (present, value) in wrapper_before.items():
            assert (name in connection.__dict__) is present
            if present:
                assert connection.__dict__[name] is value
        assert MigrationRecorder.Migration._meta.db_table == recorder_before
        assert runtime_through._meta.db_table == runtime_through_before
        assert dict(os.environ) == environment_before

    assert_restored()

    def fail_formatting(*_args: object, **_kwargs: object) -> object:
        raise RuntimeError("synthetic formatting failure")

    monkeypatch.setattr(generate_oracle_schema, "_format_custom_sql", fail_formatting)
    with pytest.raises(RuntimeError, match="synthetic formatting failure"):
        render_schema()
    assert_restored()


def test_unknown_runpython_fails_closed() -> None:
    from django.db.migrations.operations.special import RunPython

    migration_key = ("testapp", "0001_test")
    loader = SimpleNamespace(
        graph=SimpleNamespace(
            nodes={migration_key: SimpleNamespace(operations=[RunPython(lambda *_: None)])}
        )
    )
    state = SimpleNamespace(apps=SimpleNamespace(get_models=lambda **_kwargs: ()))
    with pytest.raises(
        generate_oracle_schema.UnsupportedMigrationOperation,
        match=r"testapp\.0001_test.*unsupported RunPython",
    ):
        generate_oracle_schema._collect_raw_sql(loader, state, (migration_key,))


def test_check_mode_is_mutation_free_and_uses_the_stable_contract() -> None:
    before = _SCHEMA.read_bytes()
    environment = dict(os.environ)
    for name in (
        "AGORA_ENVIRONMENT",
        "AGORA_DEBUG",
        "AGORA_PORTAL_ORIGIN",
        "AGORA_CONTENT_ORIGIN",
        "AGORA_PORTAL_SECRET_KEY",
        "AGORA_CONTENT_SECRET_KEY",
        "ENV",
        "TA_PROD_PASSWORD",
        "AGORA_ARTIFACT_ROOT",
        "DJANGO_SETTINGS_MODULE",
    ):
        environment.pop(name, None)
    environment["DJANGO_SETTINGS_MODULE"] = "agora.settings.content"
    completed = subprocess.run(
        ["uv", "run", "--locked", "python", str(_GENERATOR), "--check"],
        cwd=_ROOT,
        env=environment,
        capture_output=True,
        text=True,
        check=False,
    )
    assert completed.returncode == 0, completed.stderr
    assert completed.stdout.strip() == (
        "Oracle schema artifact is up to date: database/oracle/schema.sql"
    )
    assert _SCHEMA.read_bytes() == before


def test_check_mode_rejects_stale_artifact_without_mutation(
    tmp_path: Path,
    monkeypatch: pytest.MonkeyPatch,
    capsys: pytest.CaptureFixture[str],
) -> None:
    stale_artifact = tmp_path / "schema.sql"
    stale_artifact.write_bytes(b"stale\n")
    before = stale_artifact.read_bytes()
    monkeypatch.setattr(generate_oracle_schema, "_SCHEMA_PATH", stale_artifact)

    assert generate_oracle_schema.main(["--check"]) == 1
    captured = capsys.readouterr()
    assert captured.err.strip() == (
        "Oracle schema artifact is out of date; run "
        "uv run --locked python scripts/generate_oracle_schema.py"
    )
    assert stale_artifact.read_bytes() == before
