# Generated by Django 5.2.17 on 2026-08-26 19:05

import uuid

import django.db.models.deletion
from django.db import migrations, models

import agora.core.models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(blank=True, null=True, verbose_name="last login"),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("soeid", models.CharField(max_length=64, unique=True)),
                ("is_active", models.BooleanField(default=True)),
                ("is_administrator", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("soeid__regex", "^[A-Z0-9][A-Z0-9._-]{0,63}$")),
                        name="agora_user_canonical_soeid",
                    )
                ],
            },
            managers=[
                ("objects", agora.core.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name="Dashboard",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("published", "Published"),
                            ("unpublished", "Unpublished"),
                            ("archived", "Archived"),
                            ("deleted", "Deleted"),
                        ],
                        default="draft",
                        max_length=16,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="owned_dashboards",
                        to="persistence.user",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Revision",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("number", models.PositiveBigIntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="created_revisions",
                        to="persistence.user",
                    ),
                ),
                (
                    "dashboard",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="revisions",
                        to="persistence.dashboard",
                    ),
                ),
            ],
            options={
                "ordering": ("dashboard_id", "number"),
            },
        ),
        migrations.AddField(
            model_name="dashboard",
            name="latest_revision",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="latest_for_dashboards",
                to="persistence.revision",
            ),
        ),
        migrations.AddField(
            model_name="dashboard",
            name="published_revision",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="published_for_dashboards",
                to="persistence.revision",
            ),
        ),
        migrations.CreateModel(
            name="AuditEvent",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("event_type", models.CharField(max_length=64)),
                ("occurred_at", models.DateTimeField(auto_now_add=True)),
                ("request_id", models.UUIDField(blank=True, null=True)),
                ("metadata", models.JSONField(default=dict)),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="audit_events",
                        to="persistence.user",
                    ),
                ),
                (
                    "target_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="targeted_audit_events",
                        to="persistence.user",
                    ),
                ),
                (
                    "dashboard",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="audit_events",
                        to="persistence.dashboard",
                    ),
                ),
                (
                    "revision",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="audit_events",
                        to="persistence.revision",
                    ),
                ),
            ],
            options={
                "ordering": ("occurred_at", "id"),
            },
        ),
        migrations.CreateModel(
            name="Artifact",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "kind",
                    models.CharField(choices=[("html", "HTML"), ("csv", "CSV")], max_length=4),
                ),
                ("logical_name", models.CharField(max_length=255)),
                ("name_key", models.CharField(editable=False, max_length=1024)),
                ("storage_key", models.CharField(editable=False, max_length=76, unique=True)),
                ("byte_size", models.PositiveBigIntegerField()),
                ("media_type", models.CharField(max_length=32)),
                ("sha256", models.CharField(max_length=64)),
                (
                    "revision",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="artifacts",
                        to="persistence.revision",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="StorageReservation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("storage_key", models.CharField(editable=False, max_length=76, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("expires_at", models.DateTimeField()),
                ("verified_size", models.PositiveBigIntegerField(blank=True, null=True)),
                ("verified_sha256", models.CharField(blank=True, default="", max_length=64)),
                ("cleanup_required", models.BooleanField(default=False)),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["cleanup_required", "expires_at"],
                        name="agora_res_cleanup_expiry_idx",
                    )
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            ("storage_key__regex", "^v1/[0-9a-f]{2}/[0-9a-f]{2}/[0-9a-f]{64}$")
                        ),
                        name="agora_reservation_storage_key_format",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(("verified_sha256", ""), ("verified_size__isnull", True)),
                            models.Q(
                                ("verified_size__isnull", False),
                                models.Q(("verified_sha256", ""), _negated=True),
                            ),
                            _connector="OR",
                        ),
                        name="agora_reservation_verification_match",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("verified_sha256", ""),
                            ("verified_sha256__regex", "^[0-9a-f]{64}$"),
                            _connector="OR",
                        ),
                        name="agora_reservation_sha256_format",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="ViewerGrant",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("revoked_at", models.DateTimeField(blank=True, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="created_grants",
                        to="persistence.user",
                    ),
                ),
                (
                    "dashboard",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="viewer_grants",
                        to="persistence.dashboard",
                    ),
                ),
                (
                    "revoked_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="revoked_grants",
                        to="persistence.user",
                    ),
                ),
                (
                    "viewer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="viewer_grants",
                        to="persistence.user",
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="revision",
            constraint=models.CheckConstraint(
                condition=models.Q(("number__gt", 0)), name="agora_revision_positive_number"
            ),
        ),
        migrations.AddConstraint(
            model_name="revision",
            constraint=models.UniqueConstraint(
                fields=("dashboard", "number"), name="agora_revision_dashboard_number_unique"
            ),
        ),
        migrations.AddConstraint(
            model_name="revision",
            constraint=models.UniqueConstraint(
                fields=("dashboard", "id"), name="agora_revision_dashboard_id_unique"
            ),
        ),
        migrations.AddIndex(
            model_name="dashboard",
            index=models.Index(fields=["owner", "state"], name="agora_dash_owner_state_idx"),
        ),
        migrations.AddIndex(
            model_name="dashboard",
            index=models.Index(fields=["state", "updated_at"], name="agora_dash_state_updated_idx"),
        ),
        migrations.AddConstraint(
            model_name="dashboard",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("state__in", ["draft", "published", "unpublished", "archived", "deleted"])
                ),
                name="agora_dashboard_valid_state",
            ),
        ),
        migrations.AddConstraint(
            model_name="dashboard",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("published_revision__isnull", False), ("state", "published")),
                    models.Q(
                        models.Q(("state", "published"), _negated=True),
                        ("published_revision__isnull", True),
                    ),
                    _connector="OR",
                ),
                name="agora_dashboard_publication_state",
            ),
        ),
        migrations.AddConstraint(
            model_name="dashboard",
            constraint=models.CheckConstraint(
                condition=models.Q(("name", ""), _negated=True),
                name="agora_dashboard_name_not_empty",
            ),
        ),
        migrations.AddConstraint(
            model_name="dashboard",
            constraint=models.UniqueConstraint(
                fields=("id", "owner"), name="agora_dashboard_id_owner_unique"
            ),
        ),
        migrations.AddIndex(
            model_name="auditevent",
            index=models.Index(
                fields=["dashboard", "occurred_at", "id"], name="agora_audit_dash_time_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="auditevent",
            index=models.Index(
                fields=["actor", "occurred_at", "id"], name="agora_audit_actor_time_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="auditevent",
            index=models.Index(
                fields=["event_type", "occurred_at"], name="agora_audit_type_time_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="auditevent",
            constraint=models.CheckConstraint(
                condition=models.Q(("event_type__regex", "^[a-z][a-z0-9_.-]{2,63}$")),
                name="agora_audit_event_type_format",
            ),
        ),
        migrations.AddIndex(
            model_name="artifact",
            index=models.Index(fields=["revision", "kind"], name="agora_art_rev_kind_idx"),
        ),
        migrations.AddConstraint(
            model_name="artifact",
            constraint=models.CheckConstraint(
                condition=models.Q(("kind__in", ["html", "csv"])), name="agora_artifact_valid_kind"
            ),
        ),
        migrations.AddConstraint(
            model_name="artifact",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("kind", "html"), ("media_type", "text/html")),
                    models.Q(("kind", "csv"), ("media_type", "text/csv")),
                    _connector="OR",
                ),
                name="agora_artifact_kind_media_type",
            ),
        ),
        migrations.AddConstraint(
            model_name="artifact",
            constraint=models.CheckConstraint(
                condition=models.Q(("byte_size__gte", 0)), name="agora_artifact_nonnegative_size"
            ),
        ),
        migrations.AddConstraint(
            model_name="artifact",
            constraint=models.CheckConstraint(
                condition=models.Q(("sha256__regex", "^[0-9a-f]{64}$")),
                name="agora_artifact_sha256_format",
            ),
        ),
        migrations.AddConstraint(
            model_name="artifact",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("storage_key__regex", "^v1/[0-9a-f]{2}/[0-9a-f]{2}/[0-9a-f]{64}$")
                ),
                name="agora_artifact_storage_key_format",
            ),
        ),
        migrations.AddConstraint(
            model_name="artifact",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("logical_name", ""), _negated=True),
                    models.Q(("name_key", ""), _negated=True),
                ),
                name="agora_artifact_names_not_empty",
            ),
        ),
        migrations.AddConstraint(
            model_name="artifact",
            constraint=models.UniqueConstraint(
                fields=("revision", "name_key"), name="agora_artifact_revision_name_unique"
            ),
        ),
        migrations.AddIndex(
            model_name="viewergrant",
            index=models.Index(
                fields=["viewer", "revoked_at"], name="agora_grant_viewer_active_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="viewergrant",
            index=models.Index(
                fields=["dashboard", "revoked_at"], name="agora_grant_dash_active_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="viewergrant",
            constraint=models.UniqueConstraint(
                fields=("dashboard", "viewer"), name="agora_grant_dashboard_viewer_unique"
            ),
        ),
        migrations.AddConstraint(
            model_name="viewergrant",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("revoked_at__isnull", True), ("revoked_by__isnull", True)),
                    models.Q(("revoked_at__isnull", False), ("revoked_by__isnull", False)),
                    _connector="OR",
                ),
                name="agora_grant_revocation_fields_match",
            ),
        ),
    ]
